exclude: ^hugo/static/.*$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: check-xml
        exclude: |
          (?x)^(
              hugo/layouts/sitemap.xml|
              hugo/layouts/_default/rss.xml
          )$
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
